server:
  port: 8081
  address: 0.0.0.0

fisco:
  cert-path: conf
  group-id: group0
  peers: 127.0.0.1:20200

webase:
  sign-url: http://127.0.0.1:5004/WeBASE-Sign
  hello-address: "0xcceef68c9b4811b32c75df284a1396c7c5509561"

foodtrace:
  contract-address: "0x2af6160e266f763652f433a80b94fc13f4065303"
  jwt:
    secret: "${FOODTRACE_JWT_SECRET}"
    ttl-minutes: 120

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/foodtrace?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: "123456"